include/*/                              /usr/include/@DEB_HOST_MULTIARCH@/qt5/
lib/cmake/*                             /usr/lib/@DEB_HOST_MULTIARCH@/cmake/
lib/libQt*Web*.so                       /usr/lib/@DEB_HOST_MULTIARCH@/
lib/libQt*Web*.prl                      /usr/lib/@DEB_HOST_MULTIARCH@/
mkspecs/modules/qt_lib_*.pri            /usr/lib/@DEB_HOST_MULTIARCH@/qt5/mkspecs/modules/
mkspecs/modules-inst/qt_lib_*.pri       /usr/lib/@DEB_HOST_MULTIARCH@/qt5/mkspecs/modules/
lib/pkgconfig/Qt*Web*.pc                /usr/lib/@DEB_HOST_MULTIARCH@/pkgconfig/
