#!/bin/bash

# replace rsync line with broken up line, taking up too much horizontal space
# Also, fix port specification 

# OLD
#	rsync -arv --filter="merge ${HOME}/.config/SteamOS-Tools/repo-filter.txt" ${build_dir}/ ${REMOTE_USER}@${REMOTE_HOST}:${REPO_FOLDER}


# NEW
# rsync -arv -e 'ssh -p ${REMOTE_PORT}' --filter="merge ${HOME}/.config/SteamOS-Tools/repo-filter.txt" \
${build_dir}/ ${REMOTE_USER}@${REMOTE_HOST}:${REPO_FOLDER}

# TEST!
find . -name "build*.sh" -print0 | xargs -0 sed 's/.*rsync -arv.*/\
rsync -arv -e \'ssh -p \${REMOTE_PORT}\' --filter\="merge \${HOME}/.config/SteamOS-Tools/repo-filter.txt"\n\
\${build_dir}/ \${REMOTE_USER}@\${REMOTE_HOST}:\${REPO_FOLDER}/'
