#!/bin/bash

#
# Handles post install actions for moltengamepad
# Source from: installation/singleuser/*
#

# Services
# Reload the various services we have affected.
udevadm control --reload

# Tell the user we're done and what to do next.
echo "Installation of system files for a single user complete."
echo "Run the MoltenGamepad binary when desired."
echo ""
echo "Restart to ensure uinput permissions have been set."
