Document: mari0
Title: Debian mari0 Manual
Author: <insert document author here>
Abstract: This manual describes what mari0 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mari0/mari0.sgml.gz

Format: postscript
Files: /usr/share/doc/mari0/mari0.ps.gz

Format: text
Files: /usr/share/doc/mari0/mari0.text.gz

Format: HTML
Index: /usr/share/doc/mari0/html/index.html
Files: /usr/share/doc/mari0/html/*.html
