#!/bin/sh
set -e
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask fstrim.timer >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge fstrim.timer >/dev/null
		deb-systemd-helper unmask fstrim.timer >/dev/null
	fi
fi
# End automatically added section
