#!/bin/bash

# Set dirs
ANDROID_HOME="${HOME}/android-sdk"
mkdir -p "${ANDROID_HOME}"

cat<<-EOF
=====================================================
Note:
=====================================================
Please remember to run the post_instal.sh script
in $ANDROID_HOME by entering the below. This must
be run in a GUI environment!

$ANDROID_HOME/post_install.sh

Press enter to continue
EOF

