#!/bin/sh

set -e

case "$1" in
configure)
update-alternatives --install /usr/bin/cargo cargo /usr/lib/rust/cargo/bin/cargo 50 
update-alternatives --set cargo /usr/lib/rust/cargo/bin/cargo
;;
esac

#DEBHELPER#

