usr/include/*/solv/bitmap.h
usr/include/*/solv/chksum.h
usr/include/*/solv/dataiterator.h
usr/include/*/solv/dirpool.h
usr/include/*/solv/evr.h
usr/include/*/solv/hash.h
usr/include/*/solv/knownid.h
usr/include/*/solv/policy.h
usr/include/*/solv/poolarch.h
usr/include/*/solv/pool.h
usr/include/*/solv/poolid.h
usr/include/*/solv/pooltypes.h
usr/include/*/solv/poolvendor.h
usr/include/*/solv/problems.h
usr/include/*/solv/queue.h
usr/include/*/solv/repodata.h
usr/include/*/solv/repo.h
usr/include/*/solv/rules.h
usr/include/*/solv/selection.h
usr/include/*/solv/solvable.h
usr/include/*/solv/solverdebug.h
usr/include/*/solv/solver.h
usr/include/*/solv/solvversion.h
usr/include/*/solv/strpool.h
usr/include/*/solv/testcase.h
usr/include/*/solv/transaction.h
usr/include/*/solv/util.h
usr/lib/*/libsolv.so
usr/lib/*/cmake/
usr/lib/*/pkgconfig/libsolv.pc

# Additional, add cmake/modules/FindLibSolv.cmake 
# Debian upstream did not include this for some reason

cmake/modules/FindLibSolv.cmake usr/share/cmake/Modules/FindLibSolv.cmake
