#!/bin/bash
# Game: Streets of Rage Remake
# Home Page: http://www.bombergames.net
# Debian package created and helped by:
# - Carlos Donizete (coringao@ubuntugames.org)
# - Renan Fernandes (renan@kauamanga.com.br)
# Date: 14.08.2015
#

# Next few lines modified for SteamOS, since Zenity will not show correctly in SteamOS BPM

#SELECT=`zenity --list --window-icon=/usr/share/games/sorr/sorr.png --width=290 --height=180 --radiolist --column "AT" --column "SELECT" \
#    TRUE  "Start: Streets Of Rage Remake"\
#	FALSE "Manual Streets Of Rage Remake"`

SELECT="Start: Streets Of Rage Remake"

if echo "$SELECT" | grep $"Start: Streets Of Rage Remake"; then
	 cd "/usr/share/games/sorr/"
	 [ -d savegame ] && [ ! -d $HOME/.sorr-savegame ] && cp -r savegame $HOME/.sorr-savegame
     mkdir $HOME/.sorr-savegame
     ln -s $HOME/.sorr-savegame savegame
	 env LD_LIBRARY_PATH=data ./bgdi SorR.dat
	 rm -rf savegame
fi
if echo "$SELECT" | grep $"Manual Streets Of Rage Remake"; then
	 cd "/usr/share/games/sorr/"
     sensible-browser Manual.html
fi
