#!/bin/bash

set -e

install_packages() {
    echo "I: Installing lintian"
    apt-get -y "${APTGETOPT[@]}" install "$@"
}

install_packages lintian &> /dev/null

echo "+++ lintian output +++"

#su -c "lintian -I --show-overrides /tmp/buildd/*.changes" - pbuilder

# use this version if you don't want lintian to fail the build
su -c "lintian -I --show-overrides /tmp/buildd/*.changes; :" - pbuilder

echo "+++ end of lintian output +++"

