#!/bin/bash

set -e

install_packages() {
    apt-get -y "${APTGETOPT[@]}" install "$@"
}

echo "I: Installing lintian"
install_packages lintian &> /dev/null

echo -e "\n+++ lintian output +++\n"

#su -c "lintian -I --show-overrides /tmp/buildd/*.changes" - pbuilder

# use this version if you don't want lintian to fail the build
su -c "lintian -Ii --show-overrides /tmp/buildd/*.changes; :" - pbuilder

echo -e "\n+++ end of lintian output +++\n"

