#!/bin/bash
# example file to be used with --hookdir
#
# invoke shell if build fails.

BUILDDIR="${BUILDDIR:-/tmp/buildd}"
# Reduce package install output here, annoying when there is an error above it.
echo -e "I: NOTICE: Installing helper packages, please wait."
apt-get install -y "${APTGETOPT[@]}" vim less devscripts nano &> /dev/null
cd "$BUILDDIR"/*/debian/..
/bin/bash < /dev/tty > /dev/tty 2> /dev/tty
