#!/bin/bash

# Purpose of this is to ensure multiarch is enabled for any DIST

echo -e "I: CUSTOM ACTION (Multiarch): Checking for multi-arch support"
sleep 1s

if [[ $(dpkg --print-foreign-architectures | grep -i "i386") == "" ]]; then

	echo -e "I: CUSTOM ACTION (Multiarch): Multiarch not found"
	
	# add 32 bit support
	if dpkg --add-architecture i386; then
	
		echo -e "I: CUSTOM ACTION (Multiarch): Multiarch [Added]"
		sleep 1s
	
	else
	
		echo -e "I: CUSTOM ACTION (Multiarch): Multiarch  [FAILED]. Exiting"
		exit 1
	
	fi

else

	echo -e "I: CUSTOM ACTION (Multiarch): Multi-arch support [OK]"	

fi
