#!/bin/bash

cat<<-EOF

==NOTICE==
Please complete your installation by running the Darkmod updater.
Do you wish to run the updater now?

EOF

read -erp "Choice: [y/n] " run_updater

if [[ "${run_updater}" == "y" ]]; then

  bash /usr/share/games/darkmod/darkmod-updater.sh
  
else

  cat<<-EOF
  You can run the updater at any time by issuing the command:
  '/usr/share/games/darkmod/darkmod-updater.sh' or './darkmod-updater.sh' in the base directory
  
  EOF

fi
