audio/audio_filters/*.dsp                  usr/lib/retroarch/filters/audio
audio/audio_filters/*.so                   usr/lib/retroarch/filters/audio
debian/retroarch.cfg                       etc
gfx/video_filters/*.filt                   usr/lib/retroarch/filters/video
gfx/video_filters/*.so                     usr/lib/retroarch/filters/video
media/retroarch.svg                        usr/share/icons/hicolor/scalable/apps
usr/bin/retroarch
usr/share/applications/retroarch.desktop
