.TH DHEWM3 6 "JUNE 2014"
.SH NAME
dhewm3 \- Doom 3 engine
.SH SYNOPSIS
.B dhewm3 \fR[options]

.SH DESCRIPTION
\fBdhewm3\fR is the game engine for the DOOM 3 game. Please note, 
to play the game you'll need the game data which cannot be distriuted
by Debian
.TP
Please note that you have to patch your game data to version v1.3.1.
See /usr/share/docs/dhewm3/README.Debian for details and how to package
the game data for local installation.

.SH "SEE ALSO"
.I https://github.com/dhewm/dhewm3, /usr/share/docs/dhewm3/README.Debian