#!/bin/bash

# Append our pwd to LD_LIBRARY_PATH to handle the current run-path
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./

# Enter directory with launcher and assets
cd /usr/share/games/am2r

# <!-- OPTIONAL -->
# Start antimicro with an appropriate profile if you have trouble with your gamepad
# Place any profiles in /usr/share/games/am2r
# You will need to install the 'antimicro' application
# You can also use ds4drv for those with PS4 controllers

# antimicro --hidden --no-tray --profile x360-wireless-am2r.gamecontroller.amgp &
# ds4drv --emulate-xpad mode &

# Start game
./am2r

# Kill all instances of supplemental applications
# killall antimicro
# killall ds4drv
